title: Connecting the Village Co-op
description: A framework for establishing an on-going and honest dialog between families about their kids' social needs.
show_downloads: false
theme: jekyll-theme-architect
